apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-sandbox
  name: web-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-sandbox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-sandbox
    spec:
      containers:
      - image: docker.io/library/sandbox:0.0.1
        name: sandbox
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: websandbox
  name: websandbox
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: websandbox
  type: ClusterIP
status:
  loadBalancer: {}